micronaut:
  application:
    name: test
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: wiodjaowidjaowijdaiwjdalijwdlaiwjdlaiwjdlaiwjd

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sample
    username: sitamvan
    password: '01111997'
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
