micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - '*'
          allowedHeaders:
            - Content-type
            - Authorization
          allowedMethods:
            - POST
            - PUT
            - GET
            - DELETE
  application:
    name: api
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: naoseiquequeeuvootaaquimaiquiinfernoessecagulotemquesermuitogrande

rabbitmq:
  uri: amqp://localhost:5672

datasources:
  default:
    url: jdbc:mysql://localhost:3306/api?useSSL=false&createDatabaseIfNotExists=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
---
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
---
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
